apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: luiszunigacr/ms-client
      context: client #refers to the '/client' folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js' #If a change is made in a file that matches this pattern, 
                                #skaffold will try to push that update into the Pod.
                                #If the change doesn't match the pattern, the whole image 
                                #will be rebuilt from the context (folder)
            dest: .
    - image: luiszunigacr/ms-comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: luiszunigacr/ms-event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: luiszunigacr/ms-moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: luiszunigacr/ms-posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: luiszunigacr/ms-query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
