apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: luiszunigacr/ms-comments
          imagePullPolicy: Never #use image built locally from your image cache instead of attempting to pull from a registry
---
apiVersion: v1
kind: Service
metadata:
  name: comments-clusterip-srv
spec:
  selector:
    app: comments
  type: ClusterIP #default
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001