apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: luiszunigacr/ms-moderation
          imagePullPolicy: Never #use image built locally from your image cache instead of attempting to pull from a registry
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-clusterip-srv
spec:
  selector:
    app: moderation
  type: ClusterIP #default
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003