apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: luiszunigacr/ms-posts
          imagePullPolicy: Never #use image built locally from your image cache instead of attempting to pull from a registry
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP #default
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000