apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: luiszunigacr/ms-query
          imagePullPolicy: Never #use image built locally from your image cache instead of attempting to pull from a registry
---
apiVersion: v1
kind: Service
metadata:
  name: query-clusterip-srv
spec:
  selector:
    app: query
  type: ClusterIP #default
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002